name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print current directory
        run: pwd

      - name: Debug repository structure (root)
        run: ls -R

      - name: Debug repository structure (src/decryptor)
        run: ls -R src/decryptor || echo "Directory src/decryptor does not exist"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pytest pyinstaller black flake8

      - name: Code style check (Black)
        run: black --check src/decryptor || echo "Directory src/decryptor does not exist or no files to check"

      - name: Lint with flake8
        run: flake8 src/decryptor/ || echo "Directory src/decryptor does not exist or no files to lint"

      - name: Run tests
        run: pytest -v src/decryptor/tests/ || echo "No tests found in src/decryptor/tests/"

  deploy:
  needs: build-and-test
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/master'
  permissions:
    contents: write  

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: decryptor

    - name: Check artifact
      run: ls -la decryptor  

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: decryptor 
        tag_name: v1.0.0
        body: "Автоматический релиз"