name: CI/CD Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug repository structure
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pytest pyinstaller black flake8

      - name: Code style check (Black)
        run: black --check src/decryptor/

      - name: Lint with flake8
        run: flake8 src/decryptor/

      - name: Run tests
        run: pytest -v src/decryptor/tests/

      - name: Build executable
        run: |
          pyinstaller --onefile src/decryptor/main.py
          mkdir -p dist
          mv dist/main dist/decryptor  # Переименование файла

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: decryptor
          path: dist/decryptor

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      actions: read
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  
        with:
          name: decryptor
          path: decryptor 

      - name: Check artifact
        run: ls -la decryptor

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: decryptor/decryptor 
          tag_name: v1.0.0
          body: "Автоматический релиз"